trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: PowerShell@2
  inputs:
    filePath: 'build.ps1'
    arguments: '-OutDir $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
