trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: PowerShell@2
  inputs:
    filePath: 'build.ps1'
    arguments: '-OutDir $(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@0
  displayName: 'Publish pipeline artifact'
  inputs:
    artifactName: 'site'
    targetPath: '$(Build.ArtifactStagingDirectory)'
